# Generated by Django 5.1.1 on 2024-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AluminumCalcApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tolerance12_2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diameter_range_from", models.IntegerField()),
                ("diameter_range_to", models.IntegerField()),
                ("allowable_deviation_mean_diameter_5k", models.IntegerField()),
                ("allowable_deviation_mean_diameter_other", models.IntegerField()),
                ("allowable_deviation_point_diameter_5k", models.IntegerField()),
                ("allowable_deviation_point_diameter_other", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserTolerances12_2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alloy", models.CharField(max_length=100)),
                ("diameter", models.IntegerField()),
                ("tolerance1", models.IntegerField()),
            ],
            options={
                "db_table": "UserTolerances12_2",
            },
        ),
    ]
